# avoid color issues
term xterm-256color

## font
font_size 10.5

font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

## cursor
cursor_shape           block
cursor_blink_interval  -1
# this option is required to guarante the proper cursor shape
shell_integration	   no-cursor

## mouse interaction
mouse_hide_wait 3.0
detect_urls     yes
url_color       #268bd2
url_style       dotted
copy_on_select  no

## cancer bell
enable_audio_bell    no
visual_bell_duration 0.0

## window layout
remember_window_size  no
initial_window_width  140c
initial_window_height 34c

# TRBL
window_padding_width 2
window_padding_width 4
window_padding_width 4
window_padding_width 8

placement_strategy center

strip_trailing_spaces always

hide_window_decorations yes

# tabs
tab_bar_edge top
tab_bar_style slant
tab_bar_align left
active_tab_background #fdf6e3
active_tab_foreground #586e74
active_tab_font_style bold-italic
inactive_tab_background #eee8d5
incative_tab_foreground #657b83
inactive_tab_font_style normal
tab_bar_background #859900
tab_bar_margin_color #859900
