#!/bin/sh

if [ $(pgrep -xc panel) -gt 1 ]; then
     printf "%s" "Panel already running." >&2
     exit 1
fi

source $XDG_CONFIG_HOME/bspwm/panel/panel_cfg

bspc config top_padding $PANEL_HEIGHT

$XDG_CONFIG_HOME/bspwm/panel/info |\
lemonbar -g x18 -f "${PANEL_FONT}" -B "#FF151515" -p
