#!/bin/sh

bspc config border_width        1
bspc config window_gap          6

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# monitor list; unicode icons
# unicode chars { e1a0, e1ed, e1ec, e1dd, e1d6, e1e6 }
bspc monitor -d      

# rules
bspc rule -a Thunar state=floating
bspc rule -a Firefox desktop="^1"
bspc rule -a Ncmpcpp desktop="^4" state=floating
bspc rule -a Alsamixer desktop="^4" state=floating
bspc rule -a Htop state=floating

# autostart
$HOME/.fehbg

xsetroot -cursor_name left_ptr
