#! /bin/sh

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# monitor list; unicode icons
bspc monitor -d $(echo -ne "\ue1bf") \
$(echo -ne "\ue1ed") \
$(echo -ne "\ue1ec") \
$(echo -ne "\ue1dd") \
$(echo -ne "\ue02b") \
$(echo -ne "\ue1e6") \

# rules
bspc rule -a Thunar state=floating
bspc rule -a Firefox desktop="^1"
bspc rule -a Ncmpcpp desktop="^4" state=floating
bspc rule -a Alsamixer desktop="^4" state=floating
bspc rule -a Htop state=floating

# autostart
$HOME/.fehbg

xsetroot -cursor_name left_ptr

$XDG_CONFIG_HOME/bspwm/panel/panel &
