#! /bin/sh

bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# focus with mouse cursor
bspc config focus_follows_pointer true

# monitor list; unicode icons
bspc monitor -d $(echo -ne "\ue26d") \
$(echo -ne "\ue1ed") \
$(echo -ne "\ue1ec") \
$(echo -ne "\ue1dd") \
$(echo -ne "\ue1e6") \

# rules

# autostart
$HOME/.fehbg

xsetroot -cursor_name left_ptr

$XDG_CONFIG_HOME/bspwm/panel/panel &
